### ISSUE TITLE
getLineCount error in 0.3.0

### ISSUE THREAD

**Issue by alexodus** [oktayayr/advancedtextview#3]
```
FATAL EXCEPTION: main
      Process: com.xxx.yyy, PID: 3681
      java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineCount()' on a null object reference
      at ayar.oktay.advancedtextview.AdvancedTextView.drawJustified(AdvancedTextView.java:301)
      at ayar.oktay.advancedtextview.AdvancedTextView.drawJustified(AdvancedTextView.java:291)
```

**Comment by oktayayr** [comment]
Hi @alexodus 

Can you post your xml code? What features did you use your project?

**Comment by oktayayr** [comment]
@alexodus 

I did some tests, but I could not encounter this error. Can you give details about the case you encounter this error?

**Comment by oktayayr** [comment]
@alexodus 

This problem should be resolved. Can you test with version 0.3.5?
